services:
  - type: web
    name: mars-metadata-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
